version: '3.1'

services:
  db:
    image: mysql
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: Cearasc90@
      DATABASE_URL: "mysql://root:RuXnKeyytJqWvgyJCPOFsWqcShahoHyZ@viaduct.proxy.rlwy.net:25760/railway"
    volumes: 
      - ./api/db/data:/var/lib/mysql
    restart: always
    ports:
      - "3307:25760" # Alterado para a nova porta desejada

  adminer:
    image: adminer
    restart: always
    ports:
      - "25760:25760"